@baseUrl = http://localhost:3000

### 1. create a new user
POST {{baseUrl}}/auth/signup
Content-Type: application/json

{
  "username": "bacons",
  "password": "testpass123"
}

### 2. Login and get token
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "username": "bacons",
  "password": "testpass123"
}

### 3. Save the token from the login response
@authToken = {{login.response.body.token}}

### 4. Create a new movie (using the token from above)
POST {{baseUrl}}/movies
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "Stranger Things",
  "director": "The Duffer Brothers",
  "year": 2016
}

### 5. Get all movies
GET {{baseUrl}}/movies
Authorization: Bearer {{authToken}}

### 6. Update movie
PUT {{baseUrl}}/movies/1
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "Stranger Things",
  "director": "The duffer brothers",
  "year": 2016
}

### 7. Delete movie
DELETE {{baseUrl}}/movies/1
Authorization: Bearer {{authToken}}
